name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: Push to the directory
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pxgamer/composer-action@v2.1.0
      with:
        command: install --no-dev --optimize-autoloader --prefer-dist
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
